-- WARNING: this migration is hand-maintained, not drizzle-kit-generated.
-- Read the header of drizzle/0000_init.sql and the docblock in drizzle.config.ts before
-- adding another one: there is no 0000_snapshot.json, so `drizzle-kit generate` would
-- diff against an empty baseline and re-emit the whole schema. Hand-author the SQL,
-- append the matching entry to drizzle/meta/_journal.json, and mirror the tables in
-- src/db/schema.ts -- in that order.
--
-- NOTE ON SEPARATORS: drizzle's migrator splits this file on the breakpoint marker written
-- between each statement below, and on nothing else, and it does NOT skip comments. That
-- marker must therefore never appear inside a comment -- including this one, which is why
-- it is described here rather than quoted -- or the file is shredded into fragments that
-- will not parse. This file is a single statement, so no such marker appears in it at all.
--
-- Savings targets (spec docs/superpowers/plans/2026-08-30-savings-targets.md, Lane 1, v1.17.0).
--
-- ADDITIVE ONLY. One CREATE TABLE. There is NO table rebuild in this file.
--
-- THE FOREIGN-KEY PRAGMA IS NOT IN THIS FILE, ON PURPOSE -- see 0011's header. src/db/client.ts's
-- openDatabase() disables foreign keys around the whole migration pass and re-enables them (plus a
-- foreign_key_check) immediately after. Do not put a pragma here.
--
-- `month` (YYYY-MM) is the PRIMARY KEY, not a surrogate id: ruling T3 (household scope only -- no
-- per-person target in this release) and ruling T4 (one row per month, seeded by copy-forward, the
-- same idiom budgets/budget_rollover already use) together mean there is exactly one row per month,
-- never a second dimension to key on. Created EMPTY; nothing writes to it before
-- src/lib/savings-target.ts's saveSavingsTarget.
--
-- `mode` decides what `value` means -- 'percent' (a whole percent of that month's income) or
-- 'amount' (a fixed number of cents) -- and the two are mutually exclusive by construction: one
-- value column, so a stored row can never disagree with itself about which one is live (ruling T2:
-- "no whichever-is-greater -- a rule nobody can restate is a rule nobody can act on"). The CHECK
-- below enforces the percent range (1-100) and the amount's non-negativity in the same constraint,
-- keyed off `mode`, the same cross-column shape drizzle/0006_notifications.sql's channel/
-- secret_encrypted pairing rule and drizzle/0009_finish_line.sql's budget_rollover scope/user_id
-- pairing rule both already use.
--
-- Objects that exist ONLY in SQL and have NO Drizzle representation now number, after this
-- migration (entries 1-40 are restated verbatim from drizzle/0014_loan_direction.sql's header):
--   1. the categories.parent_id self-referencing foreign key             (0000)
--   2. the COALESCE(display_description, raw_description) index          (0000)
--   3. the COALESCE month expression index                               (0000)
--   4. every CHECK constraint on warranty_items                          (0002, extended by 0007)
--   5. every CHECK constraint on warranty_receipts                       (0002)
--   6. the warranty_search FTS5 contentless virtual table                (0002)
--   7. its six triggers, which are its ONLY writer                       (0002)
--   8. the is_subscription/name CHECK constraints on warranty_item_types (0003, re-declared 0011)
--   9. the COLLATE NOCASE collation on warranty_item_types_name_uq       (0003, re-declared 0011)
--  10. warranty_items.type_id arriving by ALTER TABLE ADD COLUMN         (0003)
--  11. the CHECK constraint on warranty_item_types.kind                  (0004, SUPERSEDED by 31)
--  12. warranty_item_types.kind itself, by ALTER TABLE ADD COLUMN        (0004)
--  13. the CHECK constraints on billing_cycle and billing_amount_cents,
--      and both columns arriving by ALTER TABLE ADD COLUMN               (0005)
--  14. the id = 1 singleton CHECK on notification_smtp                   (0006)
--  15. every other CHECK constraint on notification_smtp                 (0006)
--  16. every CHECK constraint on notification_targets, including the     (0006)
--      channel/secret_encrypted pairing rule
--  17. every CHECK constraint on notification_prefs                      (0006)
--  18. every CHECK constraint on notification_user_settings              (0006)
--  19. every CHECK constraint on notification_outbox                     (0006)
--  20. notification_prefs' WITHOUT ROWID storage class                   (0006)
--  21. the CHECK constraints on the four loan money columns, and all
--      four columns arriving by ALTER TABLE ADD COLUMN                   (0007)
--  22. every CHECK constraint on loan_matcher_rules                      (0007)
--  23. the coalesce(account_id, -1) EXPRESSION in loan_matcher_rules_uq  (0007)
--  24. every CHECK constraint on loan_payments                           (0007)
--  25. the CHECK constraint on transaction_splits                        (0009)
--  26. the CHECK constraint on account_balance_snapshots                 (0009, superseded by 0010)
--  27. both CHECK constraints on budget_rollover, including the          (0009)
--      scope/user_id pairing rule
--  28. the coalesce(user_id, -1) EXPRESSION in budget_rollover_uq        (0009)
--  29. categories.tax_relevant arriving by ALTER TABLE ADD COLUMN        (0009)
--  30. every CHECK constraint on bill_installments                       (0011)
--  31. the widened kind CHECK on warranty_item_types, now five values,   (0011)
--      SUPERSEDING entry 11
--  32. users.totp_last_counter arriving by ALTER TABLE ADD COLUMN        (0012)
--  33. bill_installments.unlinked_at arriving by ALTER TABLE ADD COLUMN  (0012)
--  34. the visibility CHECK on users, and the column arriving by        (0013)
--      ALTER TABLE ADD COLUMN
--  35. the can_sign_in CHECK on users, and the column arriving by        (0013)
--      ALTER TABLE ADD COLUMN
--  36. users.last_account_id arriving by ALTER TABLE ADD COLUMN          (0013)
--  37. merchant_rules.last_modified_by arriving by ALTER TABLE ADD COLUMN (0013)
--  38. warranty_items.budget_category_id arriving by ALTER TABLE ADD COLUMN (0013)
--  39. both CHECK constraints on audit_log                               (0013)
--  40. the loan_direction CHECK on warranty_items, and the column arriving   (0014)
--      by ALTER TABLE ADD COLUMN
--  41. both CHECK constraints on savings_targets, including the mode/value  (0015)
--      pairing rule
CREATE TABLE `savings_targets` (
	`month` text PRIMARY KEY NOT NULL,
	`mode` text NOT NULL CHECK (`mode` IN ('percent', 'amount')),
	`value` integer NOT NULL CHECK ((`mode` = 'percent' AND `value` BETWEEN 1 AND 100) OR (`mode` = 'amount' AND `value` >= 0)),
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
